server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # This "Redirects" any /api call to your Python Server
    location /api/ {
        proxy_pass http://server:5000/;
    }
}