services:
  server:
    volumes:
      - ./server:/app:delegated
      - ./ml:/ml:delegated
    command: ["uvicorn", "app:asgi_app", "--host", "0.0.0.0", "--port", "5000"]
    environment:
      - PYTHONUNBUFFERED=1
      - NPM_CONFIG_YES=true
    ports:
      - "5000:5000"
